"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Carillon.py']
DATA_FILES = ["Resources/"]
OPTIONS = {'argv_emulation': False,
		   'iconfile': "Resources/AppIcon.icns",
           'plist': {
               'CFBundleDisplayName': 'Carillon',
               'CFBundleExecutable': 'Carillon',
               'CFBundleIconFile': 'AppIcon.icns',
               'CFBundleIdentifier': 'com.iact.umontreal.ca.Carillon',
               'CFBundleInfoDictionaryVersion': '0.1',
               'CFBundleName': 'Carillon',
               'CFBundlePackageType': 'APPL',
               'CFBundleShortVersionString': '0.1',
               'CFBundleVersion': '0.1',
           }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
